export const BUTTON_TEXT = {
  EDIT: 'Edit',
  DUPLICATE: 'Duplicate',
  DELETE: 'Delete',
  ADD_NEW_DICTIONARY: 'Add new dictionary item',
  HISTORY: 'History',
  CANCEL: 'Cancel',
  SAVE_AND_NEW: 'Save & Add New',
  CLONE: 'Clone',
  SAVE: 'Save',
  ADD_NEW_CATEGORY: 'Add new category',
  CREATE_FROM_TEMPLATE: 'Create from Template',
  COPY_TO_CLIPBOARD: 'Copy to clipboard',
  EXPORT: 'Export',
}
