export const MODAL_TITLE = {
  SAVE_DICTIONARY_TERM: 'Save Dictionary Term',
  DISABLE_CATEGORY: 'Disable Category',
  DISABLE_CATEGORY_CONFIRMATION: 'Are you sure you want to disable this category?',
  ENABLE_CATEGORY: 'Enable Category',
  ENABLE_CATEGORY_CONFIRMATION: 'Are you sure you want to enable this category?',
  DELETE_CATEGORY_CONFIRMATION: 'Are you sure you want to delete this category?',
  DELETE_CATEGORY: 'Delete ',
  DISABLE_DICTIONARY: 'Disable Dictionary',
  DISABLE_DICTIONARY_CONFIRMATION: 'Are you sure you want to disable this dictionary?`',
  ENABLE_DICTIONARY: 'Enable Dictionary',
  ENABLE_DICTIONARY_CONFIRMATION: 'Are you sure you want to enable this dictionary?',
  CREATE_CATEGORY: 'Create a Category',
  CLONE_CATEGORY: 'Clone a Category',
  EDIT_CATEGORY: 'Edit a Category',
  CREATE_CATEGORY_FROM_TEMPLATE: 'Create a Category from a template',
  CATEGORY_TEMPLATES: 'Category Templates',
  CREATE_DICTIONARY: 'Create a Dictionary Entry',
  CLOSE: 'Close',
  OK: 'Ok',
  DICTIONARY_HISTORY: 'Dictionary History',
}
