export enum VehicleActions {
  FETCH_ALL_VEHICLES_BY_USER_ID = 'FETCH_ALL_VEHICLES_BY_USER_ID',
  FETCH_VEHICLE_BY_ID = 'FETCH_VEHICLE_BY_ID',
  CREATE_VEHICLE_FOR_USER_ID = 'CREATE_VEHICLE_FOR_USER_ID',
  EDIT_VEHICLE_BY_ID = 'EDIT_VEHICLE_BY_ID',
  DELETE_VEHICLE_BY_ID = 'DELETE_VEHICLE_BY_ID',
}
