export const INPUT_LABEL = {
  CATEGORY_NAME: 'What do you want your category to be called?',
  CATEGORY_LANGUAGE: 'What indicated language will this be in?',
  CATEGORY_DESCRIPTION: 'Description',
  WORDS_OR_PHRASES: 'What word(s) or phrase(s) are you looking for?',
  WHO_APPLY_TO: 'Who does this apply to?',
  WHERE_TO_HAPPEN: 'Where does the match need to happen?',
  WHEN_SHOULD_HAPPEN: 'At what point in the call do we need to look for this?',
  HOW_LONG_INTO: 'How long into the call? (MM:SS)',
  HOW_LONG_BEFORE: 'How long before the end of the call? (MM:SS)',
  PREVIOUS: 'Previous',
  NEXT: 'Next',
  DATE_RANGE: 'Date range:',
  FROM: 'From',
  TO: 'To',
  CHANGE_MADE_BY: 'Change made by:',
  TERM: 'Term:',
  LIMIT: 'Limit:',
  INCLUDE_DELETED_CATEGORIES: 'Include deleted categories:',
  SELECT_TEMPLATE: 'Select the template you want to use',
  WHICH_GROUP: 'Which group(s) should this category be applied to?',
  WHICH_USER: 'Which user(s) should this category be applied to?',
  DICTIONARY_TERM: 'Dictionary Term',
  WHAT_LANGUAGE: 'What indicated language will this be in?',
  DICTIONARY_DESCRIPTION: 'Description',
  SELECT_WEIGHTING: 'Please select the weighting of this word.',
  NEVER_MATCH: 'Never Match',
  ALWAYS_MATCH: 'Always Match',
  INCLUDE_DELETED_DICTIONARIES: 'Include deleted dictionary terms:',
  RECORDS_TO_DISPLAY: 'Records to display:',
  CATEGORY_NAME_VIEW: 'Category Name:',
  CATEGORY_LANGUAGE_VIEW: 'Indicated Language:',
  CATEGORY_DESCRIPTION_VIEW: 'Description:',
  WORDS_OR_PHRASES_VIEW: 'Words and Phrases:',
}
